import Foundation

struct Constants {
    static let METHOD_GET_SDK_VERSION: String = "METHOD_GET_SDK_VERSION"
    static let METHOD_INITIALIZE: String = "METHOD_INITIALIZE"
    static let METHOD_SCAN: String = "METHOD_SCAN"
    static let METHOD_GET_RESULT: String = "METHOD_GET_RESULT"
    static let METHOD_GET_HEATMAP: String = "METHOD_GET_HEATMAP"
    static let METHOD_SEND_FEEDBACK_COMMENT: String = "METHOD_SEND_FEEDBACK_COMMENT"
    static let METHOD_SEND_TREAD_DEPTH_RESULT_FEEDBACK: String = "METHOD_SEND_TREAD_DEPTH_RESULT_FEEDBACK"

    static let EXTRA_MEASUREMENT_UUID: String = "EXTRA_MEASUREMENT_UUID"
    static let EXTRA_LICENSE_KEY: String = "EXTRA_LICENSE_KEY"
    static let EXTRA_PLUGIN_VERSION: String = "EXTRA_PLUGIN_VERSION"
    static let EXTRA_FEEDBACK_COMMENT: String = "EXTRA_FEEDBACK_COMMENT"
    static let EXTRA_TREAD_DEPTH_RESULT_FEEDBACK: String = "EXTRA_TREAD_DEPTH_RESULT_FEEDBACK"


    static let ERROR_CODE_PLUGIN_NOT_ATTACHED_TO_ACTIVITY: String = "1000"
    static let ERROR_CODE_SDK_INITIALIZATION_FAILED: String = "1001"
    static let ERROR_CODE_GENERIC_EXCEPTION: String = "1003"
}
