import Foundation

struct Constants {
    static let METHOD_GET_SDK_VERSION = "METHOD_GET_SDK_VERSION"
    static let METHOD_INITIALIZE = "METHOD_INITIALIZE"
    static let METHOD_SCAN = "METHOD_SCAN"
    static let METHOD_IS_DEVICE_SUPPORTED = "METHOD_IS_DEVICE_SUPPORTED"
    static let METHOD_GET_RESULT = "METHOD_GET_RESULT"
    static let METHOD_GET_HEATMAP = "METHOD_GET_HEATMAP"
    static let METHOD_SEND_FEEDBACK_COMMENT = "METHOD_SEND_FEEDBACK_COMMENT"
    static let METHOD_SEND_TREAD_DEPTH_RESULT_FEEDBACK = "METHOD_SEND_TREAD_DEPTH_RESULT_FEEDBACK"
    static let METHOD_SEND_TIRE_ID_FEEDBACK = "METHOD_SEND_TIRE_ID_FEEDBACK"
    static let METHOD_SET_EXPERIMENTAL_FLAGS = "METHOD_SET_EXPERIMENTAL_FLAGS"
    static let METHOD_CLEAR_EXPERIMENTAL_FLAGS = "METHOD_CLEAR_EXPERIMENTAL_FLAGS"

    static let EXTRA_MEASUREMENT_UUID = "EXTRA_MEASUREMENT_UUID"
    static let EXTRA_LICENSE_KEY = "EXTRA_LICENSE_KEY"
    static let EXTRA_PLUGIN_VERSION = "EXTRA_PLUGIN_VERSION"
    static let EXTRA_FEEDBACK_COMMENT = "EXTRA_FEEDBACK_COMMENT"
    static let EXTRA_TREAD_DEPTH_RESULT_FEEDBACK = "EXTRA_TREAD_DEPTH_RESULT_FEEDBACK"
    static let EXTRA_TIRE_ID = "EXTRA_TIRE_ID"
    static let EXTRA_EXPERIMENTAL_FLAGS = "EXTRA_EXPERIMENTAL_FLAGS"
    static let EXTRA_TIMEOUT_SECONDS = "EXTRA_TIMEOUT_SECONDS"
    static let EXTRA_CONFIG_JSON = "EXTRA_CONFIG_JSON"
    static let EXTRA_SCAN_OPTIONS_JSON = "EXTRA_SCAN_OPTIONS_JSON"
    static let EXTRA_CUSTOM_TAG = "EXTRA_CUSTOM_TAG"
}
