package io.anyline.tiretread.flutter

object Constants {
    const val METHOD_INITIALIZE = "METHOD_INITIALIZE"
    const val METHOD_GET_SDK_VERSION = "METHOD_GET_SDK_VERSION"
    const val METHOD_SCAN = "METHOD_SCAN"
    const val METHOD_GET_RESULT = "METHOD_GET_RESULT"
    const val METHOD_GET_HEATMAP = "METHOD_GET_HEATMAP"
    const val METHOD_SEND_FEEDBACK_COMMENT = "METHOD_SEND_FEEDBACK_COMMENT"
    const val METHOD_SEND_TREAD_DEPTH_RESULT_FEEDBACK = "METHOD_SEND_TREAD_DEPTH_RESULT_FEEDBACK"
    const val METHOD_SET_EXPERIMENTAL_FLAGS = "METHOD_SET_EXPERIMENTAL_FLAGS"
    const val METHOD_CLEAR_EXPERIMENTAL_FLAGS = "METHOD_CLEAR_EXPERIMENTAL_FLAGS"

    const val EXTRA_LICENSE_KEY = "EXTRA_LICENSE_KEY"
    const val EXTRA_MEASUREMENT_UUID = "EXTRA_MEASUREMENT_UUID";
    const val EXTRA_PLUGIN_VERSION = "EXTRA_PLUGIN_VERSION";
    const val EXTRA_FEEDBACK_COMMENT = "EXTRA_FEEDBACK_COMMENT";
    const val EXTRA_TREAD_DEPTH_RESULT_FEEDBACK = "EXTRA_TREAD_DEPTH_RESULT_FEEDBACK";
    const val EXTRA_EXPERIMENTAL_FLAGS = "EXTRA_EXPERIMENTAL_FLAGS";

    const val ERROR_CODE_PLUGIN_NOT_ATTACHED_TO_ACTIVITY = "1000"
    const val ERROR_CODE_SDK_INITIALIZATION_FAILED = "1001"
    const val ERROR_CODE_GENERIC_EXCEPTION = "1003"

}
