package io.anyline.tiretread.flutter

object Constants {
    const val METHOD_INITIALIZE = "METHOD_INITIALIZE"
    const val METHOD_GET_SDK_VERSION = "METHOD_GET_SDK_VERSION"
    const val METHOD_SCAN = "METHOD_SCAN"
    const val METHOD_GET_RESULT = "METHOD_GET_RESULT"
    const val METHOD_GET_HEATMAP = "METHOD_GET_HEATMAP"

    const val EXTRA_LICENSE_KEY = "EXTRA_LICENSE_KEY"
    const val EXTRA_MEASUREMENT_UUID = "EXTRA_MEASUREMENT_UUID";

    const val ERROR_CODE_PLUGIN_NOT_ATTACHED_TO_ACTIVITY = "1000"
    const val ERROR_CODE_SDK_INITIALIZATION_FAILED = "1001"
    const val ERROR_CODE_GENERIC_EXCEPTION = "1003"

}
