# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - '*' # tag pattern on pub.dev: 'v{{version}'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Use PAT to push tags
      - env:
      - GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Publish
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1