name: Tag Push Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use PAT to push tags
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "This job is trigger"