// ignore_for_file: constant_identifier_names

class Constants {
  static const String METHOD_INITIALIZE = 'METHOD_INITIALIZE';
  static const String METHOD_GET_SDK_VERSION = 'METHOD_GET_SDK_VERSION';
  static const String METHOD_SCAN = 'METHOD_SCAN';
  static const String METHOD_GET_RESULT = 'METHOD_GET_RESULT';
  static const String METHOD_GET_HEATMAP = 'METHOD_GET_HEATMAP';
  static const String METHOD_SEND_FEEDBACK_COMMENT =
      'METHOD_SEND_FEEDBACK_COMMENT';
  static const String METHOD_SEND_TREAD_DEPTH_RESULT_FEEDBACK =
      'METHOD_SEND_TREAD_DEPTH_RESULT_FEEDBACK';

  static const String EXTRA_LICENSE_KEY = 'EXTRA_LICENSE_KEY';
  static const String EXTRA_MEASUREMENT_UUID = 'EXTRA_MEASUREMENT_UUID';
  static const String EXTRA_PLUGIN_VERSION = 'EXTRA_PLUGIN_VERSION';
  static const String EXTRA_FEEDBACK_COMMENT = 'EXTRA_FEEDBACK_COMMENT';
  static const String EXTRA_TREAD_DEPTH_RESULT_FEEDBACK =
      'EXTRA_TREAD_DEPTH_RESULT_FEEDBACK';
}
