name: Create Tag From Branch

on:
  pull_request:
    types: [closed]
    branches:
      - automation_test


jobs:
  create_tag:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "anyline-automated-release-bot"
          git config user.email "1124528+anyline-automated-release-bot@users.noreply.github.com"

      - name: Generate Tag
        id: generate_tag
        run: |
          BRANCH_NAME=${{github.event.pull_request.head.ref}}
          echo "Current branch name is: $BRANCH_NAME"
          TAG_NAME=$(echo "$BRANCH_NAME" | sed -E 's/^release\/(.*)$/v\1/')
          TAG_VERSION=$(echo "$BRANCH_NAME" | sed -E 's/^release\/(.*)$/\1/')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Push Tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Anyline ${{ env.TAG_NAME }}
          body: |
            ## What's Changed
            * https://pub.dev/packages/anyline_tire_tread_plugin/versions/${{ env.TAG_VERSION }}/changelog

            ## Documentation
            * https://pub.dev/packages/anyline_tire_tread_plugin/versions/${{ env.TAG_VERSION }}
          draft: false
          prerelease: false
