name: Create Tag From Branch

on:
  push:
    branches:
      - 'release/**'

jobs:
  create_tag:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "anyline-automated-release-bot"
          git config user.email "1124528+anyline-automated-release-bot@users.noreply.github.com"

      - name: Generate Tag
        id: generate_tag
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Current branch name is: $BRANCH_NAME"
          TAG_NAME=$(echo "$BRANCH_NAME" | sed -E 's/^release\/(.*)$/v\1/')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Push Tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}