name: Publish to pub.dev

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release. The version should be the same as version in package.json. For example, 1.0.0"
        required: true

#
#jobs:
#  publish:
#    permissions:
#      id-token: write # Required for authentication using OIDC
#    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
#    # with:
#    #   working-directory: path/to/package/within/repository

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ref/tags/${{ inputs.version }}
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart
      - name: Publish
        run: dart pub publish --force