name: Release Tagging Workflow

#on:
#  pull_request:
#    types: [closed] # Trigger the workflow when a pull request is closed
#    branches:
#      - automation_test # Only trigger for pull requests merged into the main branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release. The version should be the same as version in package.json. For example, 1.0.0"
        required: true



jobs:
  create_tag:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Check out the repository

      - name: Set up Git
        run: |
          git config user.name "${{ secrets.RELEASE_BOT_USERNAME }}" # Set Git username
          git config user.email "${{ secrets.RELEASE_BOT_EMAIL }}" # Set Git email

      - name: Generate Tag
        id: generate_tag
        run: |
          BRANCH_NAME=${{github.event.pull_request.head.ref}}
          echo "Current branch name is: $BRANCH_NAME"
#          TAG_NAME=$(echo "$BRANCH_NAME" | sed -E 's/^release\/(.*)$/v\1/')
#          TAG_VERSION=$(echo "$BRANCH_NAME" | sed -E 's/^release\/(.*)$/\1/')
#          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
#          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Push Tag
        run: |
          git tag ${{ inputs.version }} # Create the tag
          git push origin ${{ inputs.version }} # Push the tag to the repository


      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1 # Use the create-release action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token from secrets
        with:
          tag_name: ${{ inputs.version }} # Use the generated tag name
          release_name: Anyline ${{ inputs.version }} # Set the release name
          body: |
            ## What's Changed
            * https://pub.dev/packages/anyline_tire_tread_plugin/versions/${{ inputs.version }}/changelog # Link to the changelog

            ## Documentation
            * https://pub.dev/packages/anyline_tire_tread_plugin/versions/${{ inputs.version }} # Link to the documentation
          draft: false # Publish the release immediately
          prerelease: false # Mark the release as a full release
